spring:
 cloud:
   azure:
     active-directory:
       enabled: true
       profile:
         tenant-id: YOUR_AZURE_AD_TENANT_ID
       credential:
         client-id: APPLICATION_OR_CLIENT_ID
         client-secret: CLIENT_SECRET