spring:
 cloud:
   azure:
     cosmos:
       uri : YOUR_COSMOSDB_ENDPOINT
       key : YOUR_COSMOSDB_ENDPOINT_KEY
       secondaryKey : YOUR_COSMOSDB_ENDPOINT_SECONDARYKEY
       database : YOUR_COSMOSDB_NAME
       queryMetricsEnabled : true
     active-directory:
       enabled: true
       profile:
         tenant-id: YOUR_AZURE_AD_TENANT_ID
       credential:
         client-id: APPLICATION_OR_CLIENT_ID
         client-secret: CLIENT_SECRET